version: '3.8'

services:
  app:
    build: .
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-db:9092/mem:translationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - h2-db

  h2-db:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
      - "9092:9092"
    environment:
      - H2_OPTIONS=-web -webAllowOthers -webPort 8082 -tcp -tcpAllowOthers -tcpPort 9092 -ifNotExists